from os import system
from os.path import join, dirname, abspath

PROMPT_GEN: str = join(dirname(abspath(__file__)), "gptPromptGen.py")
links: tuple[tuple[str]] = (
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/Baseline-w/CHANGE-2/2/Historical/nasa-spec-5022_w-change_1_revalidation.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/Baseline-w/CHANGE-2/2/Historical/2015-06-24_NASA-SPEC-5022_Published.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/Baseline-w/CHANGE-2/2/Historical/2015-06-24_NASA-SPEC-5022_Published.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/Baseline-w/CHANGE-2/2/2021-07-16_nasa-spec-5022_w-change_2_revalidation_w-edit-admin_chgs_final.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-2/2/Historical/nasa-std-5001.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-2/2/Historical/nasa-std-5001a.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-2/2/Historical/nasa-std-5001a.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-2/2/Historical/nasa-std-5001b.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-2/2/Historical/nasa-std-5001b.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-2/2/Historical/nasa-std-5001b_w_change_1.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-2/2/Historical/nasa-std-5001b_w_change_1.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-3/3/Historical/nasa-std-5001b_w_change_2.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-3/3/Historical/nasa-std-5001b_w_change_2.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B-w/CHANGE-3/3/2022-10-24-NASA-STD-5001B-w-Change-3-Approved.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/A/0/nasa-std-5002a.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/A/0/nasa-std-5002a.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/D-w/CHANGE-1/1/Historical/nasa-std-5005.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/D-w/CHANGE-1/1/Historical/nasa-std-5005b.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/D-w/CHANGE-1/1/Historical/nasa-std-5005b.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/D-w/CHANGE-1/1/Historical/nasa-std-5005c.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/D-w/CHANGE-1/1/Historical/nasa-std-5005c.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/D-w/CHANGE-1/1/Historical/2013-06-14_nasa-std-5005d_clean_approved.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/D-w/CHANGE-1/1/Historical/2013-06-14_nasa-std-5005d_clean_approved.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/D-w/CHANGE-1/1/nasa-std-5005d_w_chg1_revalidated.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-1/1/Historical/nasa-std-5006.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-1/1/Historical/nasa-std-5006a.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-1/1/Historical/nasa-std-5006a.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-2/2/Historical/NASA-STD-5006A-w-Change-1-Revalidation.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-2/2/Historical/NASA-STD-5006A-w-Change-1-Revalidation.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-2/2/2021-11-18-NASA-STD-5006A-w-Chg-2-Reval-Final.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/Historical/nasa-std-5012.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/Historical/nasa-std-5012a.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/Historical/nasa-std-5012a.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/NASA-STD-5012B.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-1/1/Historical/nasa-std-5017.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-1/1/Historical/nasa-std-5017a.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-1/1/Historical/nasa-std-5017a.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/Historical/NASA-STD-5017A-Revalidated-w-Change-1-2.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/Historical/NASA-STD-5017A-Revalidated-w-Change-1-2.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B//2022-12-06-NASA-STD-5017B-Approved.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/Baseline-w/CHANGE-1/1/Historical/2011-08-12_NASA-STD-5018-Baseline_Final_0.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/Baseline-w/CHANGE-1/1/nasa-std-5018_revalidated.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa-std-5019.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa-std-5019a.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa-std-5019a.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa-std-5019a_w-change_1.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa-std-5019a_w-change_1.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa-std-5019a_w-change_2_final.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa-std-5019a_w-change_2_final.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa_std_i_5019_09_12_2006.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/Historical/nasa_std_i_5019_09_12_2006.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/w/CHANGE-3/3/2020-08-14_nasa-std-5019a_w-chg_3_reval_w-ed-adm_chgs-approveddocx.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/Historical/nasa-std-5020.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/Historical/nasa-std-5020a.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/Historical/nasa-std-5020a.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/Historical/nasa-std-5020a_w-chg_1.pdf"
    ),
    (
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/Historical/nasa-std-5020a_w-chg_1.pdf",
        "https://standards.nasa.gov/sites/default/files/standards/NASA/B/0/2021-08-06-nasa-std-5020b_final.pdf"
    )
)

for i in links:
    system(f"python \"{PROMPT_GEN}\" -p1 \"{i[0]}\" -p2 \"{i[1]}\"")